sudo: required
language: C
services:
- docker
before_install:
- docker pull viniciusd/vhdl_ci
script:
    - docker run -v "$(pwd)":/opt viniciusd/vhdl_ci /bin/bash -c "mkdir /opt/build && cd /opt/build && cmake .. && make all test"
notifications:
    email: false
