sudo: required
language: C
services:
- docker
before_install:
- docker info
- docker pull ghdl/ghdl:ubuntu18-llvm-5.0
script:
- docker run ghdl/ghdl:ubuntu18-llvm-5.0 /bin/bash -c "mkdir /opt/build && cd /opt/build && cmake .. && make all test"
notifications:
    email: false
